[package]
name = "UPX-Patcher"
version = "1.1.0"
edition = "2024"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[build-dependencies]
thunk-rs = "0.3.5"
embed-resource = "3.0.6"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
rand = "0.10.0"
colored = "3.1.1"
chrono = "0.4.44"
sysinfo = "0.38.3"
anyhow = "1.0.102"
